# _config.yml

# required, replace with your own information -----
title: Tiny Stories
author: Emma Wilson
description: > 
  Flash fiction from Scotland.
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

